spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpapractice1?serverTimezone=UTC&characterEncoding=UTF-8
    username: newuser
    password: 4585
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    lazy-initialization: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
       #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type: trace
