spring:
  rabbitmq:
    host: localhost
    port: 5672                 # ?? ?? (5672)
    username: guest            # ?? ????
    password: guest            # ?? ????
    virtual-host: /            # ?? ??? (?? "/")
    listener:
      simple:
        retry:
          enabled: true        # ??? ??? ??? ??
          max-attempts: 3      # ?? ??? ??
        concurrency: 1         # ?? ???
        max-concurrency: 10    # ?? ???

  datasource:
    url: jdbc:mysql://localhost:3306/rabbitmqdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: newuser
    password: 4585
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO

server:
  name: MyServer1