management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
#    git:
#      mode: "full"
  server:
    port: 8080

  endpoint:
    shutdown:
      enabled: true
    health:
#      show-details: always
      show-components: always

  endpoints:
    web:
#      base-path: "/manage"
      exposure:
        include: "*"

info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true